apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name  : devo-dev
  region: us-east-1
  version: "1.32"

vpc:
 id     : "vpc-0b3dca825cb7af41a"
 subnets:
   public:
      us-east-1f: { id: subnet-09f0abea6ee4e9be2 }  # For Load Balancer
      us-east-1a: { id: subnet-0ed83848aafbae723 }  # For Load Balancer
   private:
      us-east-1b: { id: subnet-0ecdff9dfda8d1f2b }  # For Worker Nodes
      us-east-1d: { id: subnet-0a8f65ddfa4cdeeb0 }  # For Worker Nodes

managedNodeGroups:
  - name: general
    instanceType: t3.small
    desiredCapacity: 2
    labels:
      role: general
    volumeSize: 50
    privateNetworking: true
