apiVersion: apps/v1
kind: Deployment
metadata:
  name: snake
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: snake
  template:
    metadata:
      labels:
        app: snake
    spec:
      containers:
      - name: snake
        image: cylinder47/snake:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 2406
        env:
          - name: FLASK_ENV
            value: production
---
apiVersion: v1
kind: Service
metadata:
  name: snake-service
  namespace: default
spec:
  selector:
    app: snake
  ports:
    - protocol: TCP
      port: 80
      targetPort: 2406
  type: ClusterIP
